name: "Lock Threads"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/lock-threads@v4
        with:
          issue-inactive-days: "3"
          pr-inactive-days: "14"
          add-issue-labels: "stale"
          add-pr-labels: "stale"
          exclude-any-issue-labels: "help-wanted"
          exclude-any-pr-labels: "help-wanted"
          issue-lock-reason: ""
          pr-lock-reason: ""
